# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30f782448be50b79c7ed40d30d480cb3"
name = "Ai_Bot_Test2"
handle = "ai-bot-test2"
application_url = "https://cartrecover-bot.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_products,read_customers,write_price_rules"

[auth]
redirect_urls = [ "https://cartrecover-bot.onrender.com/auth/callback" ]

[pos]
embedded = false
